analyzer:
  errors:
    avoid_function_literals_in_foreach_calls: ignore
    library_prefixes: ignore
    library_private_types_in_public_api: ignore
    must_be_immutable: ignore

linter:
  
  rules:
    avoid_print: true
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_typing_uninitialized_variables: false
    use_key_in_widget_constructors: true
    use_build_context_synchronously: true
    use_full_hex_values_for_flutter_colors: true
    prefer_relative_imports: true
    sort_child_properties_last: true
    annotate_overrides: true
    await_only_futures: true
    avoid_relative_lib_imports: true
    avoid_returning_null_for_void: true
    avoid_unnecessary_containers: true
    empty_catches: true
    empty_constructor_bodies: true
    empty_statements: true
    no_leading_underscores_for_local_identifiers: false
    no_logic_in_create_state: true
    prefer_is_empty: false
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    avoid_init_to_null: true
    prefer_final_fields: true
    unnecessary_null_in_if_null_operators: true