name: haring_task
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0-163.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3
  intl: ^0.20.0
  share_plus: ^10.0.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/png/
  fonts:
    - family: NeueHaasDisplay
      fonts:
        - asset: assets/fonts/NeueHaasDisplayBlack.ttf
        - asset: assets/fonts/NeueHaasDisplayBold.ttf
        - asset: assets/fonts/NeueHaasDisplayLight.ttf
        - asset: assets/fonts/NeueHaasDisplayMedium.ttf
