name: haring_task
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.0-163.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3
  flutter_offline: ^4.0.0
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  get_it: ^8.0.2
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/png/
  fonts: 
    - family: NeueHaasDisplay
      fonts:
        - asset: assets/fonts/NeueHaasDisplayBlack.ttf
        - asset: assets/fonts/NeueHaasDisplayBold.ttf
        - asset: assets/fonts/NeueHaasDisplayLight.ttf
        - asset: assets/fonts/NeueHaasDisplayMedium.ttf
