class AppStrings {
  static const String appName = 'Sayed Moataz';
  static const String noRoutesFound = 'No Routes Found';
  static const String visitorInfo = 'Visitor Info';
  static const String asterisk = '*';
  static const String requiredField = 'Required Field';
  static const String newVisitor = 'New Visitor Pre-Access';
  static const String address = 'Villa 45, Palm Crescent Compound, Al Sufouh 2';
  static const String nextStep = 'Next Step';
  static const String shareButton = 'Share This QR Code';
  static const String Name = 'Name';
  static const String NameHint = 'John Doe';
  static const String Phone = 'Phone';
  static const String PhoneHint = '+201xxxxxxxxx';
  static const String Email = 'Email';
  static const String EmailHint = 'John_don@example.com';
  static const String date = 'Expected Visit Date';
  static const String dateHint = 'Click to pick a date';
  static const String time = 'Expected Visit Time';
  static const String timeHint = 'Click to pick a time';
  static const String idNumber = 'ID Number';
  static const String idNumberHint = 'E.g.xxxxxxxxxxxxxx';
  static const String visitReason = 'Visit Reason';
  static const String required = 'This Field Is Required';
  static const String yourCode = 'Your Visitor QR Code';
  static const String successQuote = 'was generated successfully!';
  static const String backHome = 'Back To Home';
  static const String shareCodeString = 'Share this screen with your visitor so they can access it';
}
